service: FriedRice

provider:
  name: aws
  runtime: nodejs6.10
  profile: alexa
  stage: production
  region: ap-northeast-1

functions:
  friedSound:
    handler: handler.main
    events:
      - alexaSkill

