service: FriedRice

provider:
  name: aws
  runtime: nodejs8.10
  profile: alexa
  stage: production
  region: ap-northeast-1

functions:
  friedSound:
    handler: handler.main
    events:
      - alexaSkill:
          appId: amzn1.ask.skill.dab29912-64b6-4424-8748-26e22dc21589
          enabled: true

